language: python
# Run on Travis CI's docker infrastructure
sudo: false

matrix:
  include:
    - python: 2.6
      env: TOXENV=py26 CC=gcc
    - python: 2.7
      env: TOXENV=py27 CC=gcc
    - python: 3.3
      env: TOXENV=py33 CC=gcc
    - python: 3.4
      env: TOXENV=py34 CC=gcc
    - python: 3.5
      env: TOXENV=py35 CC=gcc
    - python: 3.6
      env: TOXENV=py36 CC=gcc
    - python: pypy
      env: TOXENV=pypy CC=gcc
    - python: 2.6
      env: TOXENV=py26 CC=clang
    - python: 2.7
      env: TOXENV=py27 CC=clang
    - python: 3.3
      env: TOXENV=py33 CC=clang
    - python: 3.4
      env: TOXENV=py34 CC=clang
    - python: 3.5
      env: TOXENV=py35 CC=clang
    - python: 3.6
      env: TOXENV=py36 CC=clang
    - python: pypy
      env: TOXENV=pypy CC=clang
    - python: 2.7
      env: TOXENV=pep8
    - env: TOXENV=packaging
    - python: 3.5
      env: TOXENV=py3pep8
    - language: generic
      os: osx
      osx_image: xcode7.3
      env: TOXENV=py27
    - language: generic
      os: osx
      osx_image: xcode7.3
      env: TOXENV=py35

install: .travis/install.sh

script: .travis/run.sh

branches:
  only:
    - master
